LangString addOrReinstall ${LANG_ENGLISH} "Repair or reinstall"
LangString alreadyInstalled ${LANG_ENGLISH} "AIMonitorDesktop is installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Choose repair or uninstall to continue."
LangString appRunning ${LANG_ENGLISH} "AIMonitorDesktop is running. Close it before continuing."
LangString appRunningOkKill ${LANG_ENGLISH} "AIMonitorDesktop is running.$\nSelect OK to close it and continue."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose a maintenance action."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how to install AIMonitorDesktop."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Keep the existing installation"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Installing an older version directly is not allowed"
LangString failedToKillApp ${LANG_ENGLISH} "AIMonitorDesktop could not be closed. Close it manually and try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing Microsoft WebView2..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer AIMonitorDesktop version is installed. Uninstall it before installing this older version."
LangString older ${LANG_ENGLISH} "older or unknown"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "AIMonitorDesktop version $R4 is installed. We recommend uninstalling it before continuing."
LangString silentDowngrades ${LANG_ENGLISH} "Silent downgrades are disabled. Use the graphical installer instead.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "AIMonitorDesktop could not be uninstalled."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall AIMonitorDesktop"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall the existing version first"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "Microsoft WebView2 could not be installed. AIMonitorDesktop requires it to run. Restart the installer and try again."
LangString webview2DownloadError ${LANG_ENGLISH} "Microsoft WebView2 download failed: $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "Microsoft WebView2 download completed"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading Microsoft WebView2..."
LangString webview2InstallError ${LANG_ENGLISH} "Microsoft WebView2 installation failed with code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "Microsoft WebView2 installation completed"
LangString deleteAppData ${LANG_ENGLISH} "Also delete AIMonitorDesktop local data"
