LangString addOrReinstall ${LANG_SIMPCHINESE} "修复或重新安装"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装 AIMonitorDesktop"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已安装。请选择修复安装或卸载。"
LangString appRunning ${LANG_SIMPCHINESE} "AIMonitorDesktop 正在运行，请先关闭应用后重试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "AIMonitorDesktop 正在运行。$\n点击“确定”关闭应用并继续。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择要执行的维护操作。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择 AIMonitorDesktop 的安装方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "保留现有安装并继续"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不能直接安装旧版本"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法关闭 AIMonitorDesktop，请手动关闭后重试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 Microsoft WebView2..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "系统中已安装更新版本的 AIMonitorDesktop。若要安装当前旧版本，请先卸载现有版本。"
LangString older ${LANG_SIMPCHINESE} "旧版本或未知"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "系统中已安装 $R4 版本的 AIMonitorDesktop。建议先卸载现有版本再继续。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "安装器不允许静默降级，请使用图形安装界面。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载 AIMonitorDesktop。"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 AIMonitorDesktop"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "先卸载现有版本"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "Microsoft WebView2 安装失败。AIMonitorDesktop 需要 WebView2 才能运行，请重新启动安装器。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "Microsoft WebView2 下载失败：$0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "Microsoft WebView2 下载完成"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 Microsoft WebView2..."
LangString webview2InstallError ${LANG_SIMPCHINESE} "Microsoft WebView2 安装失败，错误代码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "Microsoft WebView2 安装完成"
LangString deleteAppData ${LANG_SIMPCHINESE} "同时删除 AIMonitorDesktop 的本地数据"
